@startuml
actor user

participant Authenticator as a
participant Auth0Authenticator as auth0
participant DatabaseHelperClass as db

activate user
        user -> a: register(username)
        activate a
                        a -> db: usernameAvailable(username)
                        activate db
                                alt username is unique
                                   db --> a: true
a -> auth0: loginWithPopup()
activate auth0
          
                        auth0 -> user: Request login credentials (Github/Google)
                        user --> auth0: login credentials (Github/Google)
auth0 --> a: JWT
deactivate auth0
a -> db: addUser(username, email)
db --> a: Success
                                        a --> user: Success
                                else
                                        db --> a: false
deactivate db
                                        a --> user: Error: pick a different username
deactivate a
                                end
                

deactivate user
@enduml
