@startuml
actor user


participant Player as U
participant DatabaseHelperClass as db

activate user
user -> U: getStats()

                activate U
                U -> db: getWinsAndLosses(username)
                        activate db
                db --> U: [numbers]
U --> user: statistics
                                deactivate db

                deactivate U
deactivate user
@enduml
