@startuml
actor user
'expand paddle

participant Player as P
participant Paddle as pad

activate user
user -> P: applyPowerup(ExpandedPaddle)
activate P
P -> pad: changePaddleWidth(ratio)
activate pad
pad --> P: success
deactivate pad
P --> user: success
deactivate P
        
deactivate user
@enduml
