@startuml
actor user

participant Authenticator as a
participant Auth0Authenticator as auth0

activate user
        user -> a: authenticateWithAuth0(username)
        activate a
                a -> auth0: . loginWithPopup()
deactivate a
                activate auth0
                        auth0 -> user: Request login credentials (Github/Google)
                        user --> auth0: login credentials (Github/Google)
                        auth0 --> user: JWT (contains email + token)
'                        user -> a: Authenticate (JWT)
'                        a -> auth0: verify JWT
'                        alt JWT is valid
'                                auth0 --> a: valid
'                                a --> user: Success
'                        else
'                                auth0 --> a: invalid
'                                a --> user: Error: Invalid JWT
'                        end

                deactivate auth0
                
deactivate user
@enduml
