@startuml
actor user

participant Player as P
participant Game as G
'participant Paddle as pad

activate user
user -> P: applyPowerup(ColourBackground)
activate P
P -> G: changeBackground(color)
activate G
G --> P: success
deactivate G
P --> user: success
deactivate P
        
deactivate user
@enduml
