actor user
participant Game
participant User as U
participant DatabaseHelperClass as db

activate user
        loop
        user -> Game: play game
        activate Game
                        Game --> user: game event
                end
                
        Game -> U: add XP
        deactivate Game
        activate U
        
                U -> db: update XP
        activate db
                db --> U: ok
                U -> db: check current XP
                db --> U: XP
        deactivate db
                alt XP is high enough
                        U --> user: new skin available
                else
                        U --> user
                end
deactivate user
deactivate U
