actor user
participant Game
participant Player as U
participant DatabaseHelperClass as db

activate user
''        loop
        user -> Game: endGame()
        activate Game
''                        Game --> user: game event
''                end
                
        Game -> U:. earnXP(xp)
        deactivate Game
        activate U
        
                U -> db: updateXP(username, xp)
        activate db
                db --> U: success
                U -> db: getXP(username)
                db --> U: XP
        deactivate db
                alt XP is high enough
                        U --> user: notification: new skin available
                else
                        U --> user: no new skin available
                end
deactivate user
deactivate U
