@startuml
actor user

participant Player as U
participant AuthenticationClass as A
participant DatabaseHelperClass as db


activate user
        user -> U: getAvailableSkins()
        activate U
                U -> A: playerAuthenticated()
                activate A
                        alt user authenticated
                                A --> U: true
                                U -> db: getXP()
                                activate db
                                db --> U: XP
                                        U --> user: [colors]
                                        user -> U: setPaddleSkin(color)
                                        U -> db: savePaddleColor(username, color)
                                        db --> U: success
                                        U --> user: success
                deactivate db
                                else
                                        A --> U: false
                                        U --> user: Error: unauthenticated
                                end
                deactivate A
                                
        deactivate U
        
deactivate user
@enduml
