@startuml
actor user

participant Lobby as L
participant Game as G
activate user

        user -> L: createLobby()
        activate L
                L --> user: lobby ID
                user -> L: startGame
                alt 3 or more users in lobby
                        L -> G : new Game(num_sides)
                        activate G
                        G --> user: Game
                        else
                                L --> user: Error: not enough players to start game
                                end
        deactivate L
                deactivate G
deactivate user
@enduml
