@startuml
actor user

participant Lobby as L
activate user

        user -> L: getLobbyID()
        activate L
                L --> user: link with lobby ID
        deactivate L
deactivate user
@enduml
