@startuml
actor user

participant Lobby as L
'participant Game as G
activate user

        user -> L: joinLobby(user_id, websocket, lobby_id)
        activate L
                L --> user: success
        deactivate L
deactivate user
@enduml
