@startuml
actor user

participant Game as G


activate user

'        user -> G: begin game
'        activate G
'        G --> user: game
                loop
                        user -> G: updateClientState(game)
                        G --> user: render game
                end
        activate G
                deactivate G
deactivate user
@enduml
