@startuml
actor user

participant Game as G
participant Player as U
participant DatabaseHelperClass as db

activate user

                user -> G: endGame()
                activate G
         

                G -> U:. earnXP(xp)
deactivate G
                activate U
                        U -> db: updateXP(username, xp)
                        activate db
                                db --> U: new XP
                                deactivate db
'                        U --> G: ok
U --> user: notification: updated XP
deactivate user
                        deactivate U
@enduml
