@startuml
actor user

participant Leaderboard as L
participant DatabaseHelperClass as db

activate user
user -> L: getGlobalLeaderboard()
        activate L
                L -> db: getXPForTopPlayers()
                activate db
                db --> L: (usernames, xp)[]
                deactivate db
                L --> user: global leaderboard
deactivate L
@enduml
