version: '3'

services:
################################################################################
  mongo:
      image: mongo
      container_name: mongoo
      restart: unless-stopped
      ports:
       - 27017:27017
        
  polyserver:
    build:
      context: .
    container_name: polyserver
    ports:
      - 5000:5000
    environment:
      MONGOURL: "mongodb://mongoo:27017"
    restart: unless-stopped
    depends_on: 
      - mongo